config/routes.rb
Rails.application.routes.draw do
  resources :resumes
  root 'positions#index'
  devise_for :users

  resources :applicants
  resources :positions do
    resources :applicants, only: [:index], controller: 'positions_applicants'
  end
  resources :companies do
    resources :positions, only: [:index], controller: 'companies_positions'
  end
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id          :uuid             not null, primary key
#  career      :integer          not null
#  city        :string
#  contract    :integer          not null
#  description :text
#  name        :string           not null
#  publish     :boolean          not null
#  remote      :boolean          not null
#  salary_max  :decimal(10, 2)   default(0.0), not null
#  salary_min  :decimal(10, 2)   default(0.0), not null
#  state       :string
#  summary     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :uuid             not null
#
# Indexes
#
#  index_positions_on_company_id  (company_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#
class Position < ApplicationRecord
  belongs_to :company

  has_many :applicants, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  enum career: {
    developer: 0,
    designer: 1,
    marketing: 2,
    sales: 3,
    support: 4,
    management: 5,
    finance: 6,
    hr: 7,
    other: 8
  }

  enum contract: {
    clt: 0,
    pj: 1,
    frelancer: 2
  }

  accepts_nested_attributes_for :tags

  validates_presence_of :name, :career, :contract, :company_id

  # validade max caracter in summary
  validates :summary, length: { maximum: 500 }

  scope :with_tags, lambda { |tag_names|
    joins(:tags).where(tags: { name: tag_names }).distinct
  }

  attr_accessor :existing_tag_ids

  after_save :assign_existing_tags

  def self.ransackable_attributes(_auth_object = nil)
    %w[name career contract remote city state summary description publish company_id]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[company tags]
  end

  private

  def assign_existing_tags
    return unless existing_tag_ids.present?

    current_tag_ids = tags.pluck(:id)

    tags_to_remove_ids = current_tag_ids - existing_tag_ids

    taggings.where(tag_id: tags_to_remove_ids).destroy_all

    tags_to_add = Tag.where(id: existing_tag_ids - current_tag_ids)
    tags << tags_to_add
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: %i[show edit update destroy]
  before_action :set_search, only: %i[index]

  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @positions = @search.result
    @pagy, @positions = pagy(@positions)
  end

  def show; end

  def new
    @position = Position.new
    @position.tags.build
    @existing_tags = Tag.all
  end

  def edit; end

  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to position_url(@position), notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to position_url(@position), notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company = @position.company
    @position.destroy

    flash.now[:success] = 'Vaga deletada com sucesso!'

    respond_to do |format|
      format.turbo_stream { render turbo_stream: [update_positions, toast] }
      format.json { head :no_content }
    end
  end

  private

  def set_position
    @position = Position.includes(:tags, :company).find(params[:id])
  end

  def update_positions
    @positions = @company.positions
    @pagy, @positions = pagy(@positions)

    turbo_stream.update 'company_positions', partial: 'companies_positions/positions_table',
                                             locals: { positions: @positions, pagy: @pagy }
  end

  def set_search
    @search = Position.includes(:tags, :company).order(created_at: :desc).ransack(params[:q])
  end

  def position_params
    params.require(:position).permit(:name, :career, :contract, :remote, :city, :state, :summary, :description,
                                     :publish, :company_id, existing_tag_ids: [], tags_attributes: %i[id name])
  end
end

app/views/positions/_form.html.erb
<%= simple_form_for(@position) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="card-body">
    <%= f.input :name %>
    <div class="row">
    <%= f.input :career, collection: Position.careers.keys.map { |career| [t("activerecord.attributes.position.careers.#{career}"), career] },
     include_blank: false , wrapper_html: { class: 'col' } %>
    <%= f.input :contract, collection: Position.contracts.keys.map { |contract| [t("activerecord.attributes.position.contracts.#{contract}"), contract] },
     include_blank: false , wrapper_html: { class: 'col' } %>
    </div>
    <div class="form-group">
      <div class="custom-control custom-switch">
        <%= f.check_box :remote, class: 'custom-control-input' %>
        <%= f.label :remote, class: 'custom-control-label'%>
      </div>
    </div>
    <div class="row">
      <%= f.input :city, wrapper_html: { class: 'col' } %>
      <%= f.input :state, wrapper_html: { class: 'col' } %>
    </div>

    <%= f.input :summary , input_html: { rows: 5 } %>
    <%= f.input :description, input_html: { rows: 10 } %>
    <div class="form-group">
      <div class="custom-control custom-switch">
        <%= f.check_box :publish, class: 'custom-control-input' %>
        <%= f.label :publish, class: 'custom-control-label'%>
      </div>
    </div>
    <%= f.association :company, include_blank: false %>

    <div class="form-group">
      <%= f.label :existing_tag_ids, "Selecione algumas habilidades pra sua vaga" %>
      <%= f.select :existing_tag_ids, Tag.all.map { |tag| [tag.name, tag.id] }, {
        include_blank: false,
        selected: position.tags.map(&:id)
      }, { multiple: true, class: "form-control select2", data: { controller: "select2" } } %>
    </div>
  </div>

<div class="card-footer text-right">
  <%= f.submit "Salvar", class: "btn btn-primary" %>
  <%= link_to "Cancelar", positions_path, class: "btn btn-secondary" %>
</div>

<% end %>

app/views/positions/_position.html.erb
<div class="card-body">
    <% if user_signed_in? && current_user == position.company.user %>
        <div class="row">
            <div class="col-12 col-sm-6">
                <div class="callout callout-info">
                    <%= link_to position_applicants_path(position), class: "link-primary" do %>
                    Total inscritos <span class="float-right badge bg-primary"><%= position.applicants.count %></span>
                    <% end %>
                </div>
            </div>
            <div class="col-12 col-sm-6">
                <div class="callout callout-info">
                    <%= link_to applicants_path(position), class: "link-primary" do %>
                    Total inscritos <span class="float-right badge bg-primary"><%= position.applicants.count %></span>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
    <div class="row">
        <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
            <div class="row">
                <div class="col-12 col-sm-4">
                    <div class="info-box bg-light">
                        <div class="info-box-content">
                            <span class="info-box-text text-center text-muted">Tipo de contratação</span>
                            <span class="info-box-number text-center text-muted mb-0"><%= position.contract.upcase %></span>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-4">
                    <div class="info-box bg-light">
                        <div class="info-box-content">
                            <span class="info-box-text text-center text-muted">Area de atuação</span>
                            <span class="info-box-number text-center text-muted mb-0">
                                <%= I18n.t("enums.position.career.#{position.career}") %>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-4">
                    <div class="info-box bg-light">
                        <div class="info-box-content">
                            <% if position.remote %>
                                <span class="info-box-text text-center text-muted">Local de trabalho</span>
                                <span class="info-box-number text-center text-muted mb-0">Remoto</span>
                            <% else %>
                                <span class="info-box-text text-center text-muted">Local de trabalho</span>
                                <span class="info-box-number text-center text-muted mb-0"><%= position.state %></span>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <h4>Descrição da vaga</h4>
                    <div class="post">
                        <p>
                            <%= position.description %>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
            <div class="row mb-4">
                <div class="user-block">
                        <% if position.company.logo.attached? %>
                            <%= image_tag position.company.logo, class: "img-circle img-bordered-sm", style: "max-width: 100px; object-fit: cover;", alt: "Company profile picture" %>
                        <% else %>
                            <%= image_tag "default-company-logo.png", class: "img-circle img-bordered-sm", style: "max-width: 100px; object-fit: cover;", alt: "Company profile picture" %>
                        <% end %>
                        <span class="username">
                        <%= link_to position.company.name, company_path(position.company) %>
                        </span>
                        <span class="description">Data da publicação: <%= position.created_at.strftime("%d/%m/%Y") %></span>
                </div>
            </div>

            <p class="text-muted">
                <%= position.company.summary %>
            </p>
            <br>
            <div class="text-muted">
                <p class="text-sm">Quantidade de colaboradores
                    <b class="d-block">Atualmente possui <%= position.company.employee_count %> colaboradores</b>
                </p>
                <p class="text-sm">Data da Fundação
                    <b class="d-block"><%= position.company.founded_date.strftime("%d/%m/%Y") %></b>
                </p>
            </div>
            <h5 class="mt-5 text-muted">Contato</h5>
            <ul class="list-unstyled">
                <li>
                    <a href="mailto:<%= position.company.contact_email %>" class="btn-link text-secondary">
                        <i class="fa-solid fa-envelope mr-2"></i>Email: <%= position.company.contact_email %>
                    </a>
                </li>
                <li>
                    <P class="text-secondary">
                        <i class="fa-solid fa-phone mr-2"></i>Telefone: <%= position.company.contact_phone %>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/positions/_position_card.html.erb
<div id="<%= dom_id position %>" class="col-12 col-lg-6 p-2 d-flex align-items-stretch flex-column">
    <div class="card bg-light d-flex flex-fill">
        <div class="card-header text-muted border-bottom-0">
            <%= position.company.name %>
        </div>
        <div class="card-body d-flex flex-column justify-content-between">

                <div class="row mb-2">
                    <div class="col-9">
                        <h2 class=""><b><%= position.name %></b></h2>
                        <ul class="text-muted d-flex flex-wrap gap-3 p-0" style="list-style-type: none;">
                          <li class="d-flex align-items-center gap-2">
                            <i class="fa-regular fa-calendar-days"></i>
                            <%= position.created_at.strftime("%d/%m/%Y") %>
                          </li>
                          <li class="d-flex align-items-center gap-2">
                            <i class="fa-solid fa-location-dot"></i>
                            <% if position.remote %>
                              Remoto
                            <% else %>
                              <%= position.state %>
                            <% end %>
                          </li>
                        </ul>
                        <div>
                          <ul class="list-inline">
                              <% position.tags.each do |tag| %>
                                  <li class="list-inline-item">
                                      <span class="badge bg-primary"><%= tag.name %></span>
                                  </li>
                              <% end %>
                          </ul>
                        </div>
                    </div>
                    <div class="col text-center">
                        <img src="https://t.ctcdn.com.br/lvns56iaSMyHvyTur4JeYS_NYeY=/i606944.png" alt="user-avatar" class="img-circle img-thumbnail">
                    </div>
                </div>

                <div class="row">
                    <p class="card-text clamp-text">
                        <%= position.summary %>
                    </p>
                </div>
        </div>
        <div class="card-footer">
            <div class="text-right">
                <%= link_to position, class: "btn btn-sm btn-primary", data: { turbo_frame: "_top" } do %>
                <i class="fas fa-user"></i>
                Detalhes da vaga
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render "form", position: @position %>

<br>

<div>
  <%= link_to "Show this position", @position %> |
  <%= link_to "Back to positions", positions_path %>
</div>

app/views/positions/index.html.erb
<%= render "shared/content_header", page_title: "Lista de vagas" %>

<div class="d-flex justify-content-center content-header">
  <%= search_form_for @search, url: positions_path, method: :get, class: "position-relative col-md-6", data: { turbo_frame: "positions_frame" } do |form| %>
    <div class="form-group d-flex flex-column justify-content-center align-items-center">
      <%= form.label :tags_id_in, "Pesquise sua vaga por Tags" %>
      <%= form.select :tags_id_in, Tag.all.pluck(:name,:id), { include_blank: false }, { multiple: true, class: "form-control select2", data: { controller: "select2" }, onchange: "this.form.requestSubmit()" } %>
    </div>
  <% end %>
</div>

<%= turbo_frame_tag "positions_frame" do %>
  <div class="d-flex flex-wrap">
    <% @positions.each do |position| %>
      <%= render "position_card", position: position %>
    <% end %>
  </div>
<% end %>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/positions/new.html.erb
<%= render "shared/content_header", page_title: "Nova Vaga" do %>
  <li class="breadcrumb-item"><%= link_to "Vagas", positions_path %></li>
  <li class="breadcrumb-item active">Nova Vaga</li>
<% end %>


<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title pt-1">Adicione uma nova vaga</h3>
    </div>
    <%= render "form", position: @position %>
</div>

app/views/positions/show.html.erb
<%= render "shared/content_header", page_title: "Visualizar vaga" do %>
  <li class="breadcrumb-item"><%= link_to "Vagas", positions_path %></li>
  <li class="breadcrumb-item active">Detalhes</li>
<% end %>

<div class="card card-primary">
    <div class="card-header">
        <div class="d-flex justify-content-center aling-items-center">
            <h3 class="card-title mb-0 p-2"><span class="fw-bold">Detalhes da vaga:</span> <%= @position.name %></h3>
        </div>
    </div>

    <%= render @position %>

    <div class="card-footer text-right">
      <%= link_to "Aplicar para a vaga", new_applicant_path(position_id: @position.id), class: "btn btn-primary" %>
      <%= link_to "Cancelar inscrição", positions_path, class: "btn btn-secondary" %>
    </div>
</div>