config/routes.rb
Rails.application.routes.draw do
  resources :resumes
  root 'positions#index'
  devise_for :users

  resources :applicants
  resources :positions do
    resources :applicants, only: [:index], controller: 'positions_applicants'
  end
  resources :companies do
    resources :positions, only: [:index], controller: 'companies_positions'
  end
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id             :uuid             not null, primary key
#  contact_email  :string
#  contact_phone  :string
#  employee_count :integer
#  founded_date   :date
#  name           :string
#  summary        :text
#  url            :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :uuid             not null
#
# Indexes
#
#  index_companies_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Company < ApplicationRecord
  belongs_to :user
  has_one_attached :logo, dependent: :destroy

  validates :name, :summary, :founded_date, :employee_count, presence: true
  validates :contact_email, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_many :positions, dependent: :destroy
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]
  before_action :redirect_if_company_present, only: [:new]
  before_action :purge_logo, only: [:update]
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :authorize_company, only: %i[edit update destroy]

  def index
    @pagy, @companies = pagy(Company.includes(:user).order(updated_at: :desc), items: 5)

    respond_to do |format|
      format.html
      format.json do
        render json: {
          companies: ActiveModelSerializers::SerializableResource.new(@companies, each_serializer: CompanySerializer),
          meta: pagy_metadata(@pagy).slice(:count, :page, :items, :pages, :prev, :next)
        }
      end
    end
  end

  def show; end

  def new
    @company = current_user.build_company
  end

  def edit; end

  def create
    @company = current_user.build_company(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy!

    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def authorize_company
    authorize @company, policy_class: CompanyPolicy
  end

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :url, :logo, :description, :summary, :founded_date, :employee_count,
                                    :contact_email, :contact_phone)
  end

  def purge_logo
    @company.logo.purge if @company.logo.attached?
  end

  def redirect_if_company_present
    redirect_to edit_company_url(current_user.company) if current_user.company.present?
  end
end

app/views/companies/components/_company_positions_table.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Simple Full Width Table</h3>
    <div class="card-tools">
      <ul class="pagination pagination-sm float-right">
        <li class="page-item"><a class="page-link" href="#">«</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">»</a></li>
      </ul>
    </div>
  </div>
  <div class="card-body p-0">
    <table class="table">
      <thead>
        <tr>
          <th style="width: 10px">id</th>
          <th>Nome</th>
          <th>Status</th>
          <th style="width: 40px">Publicação</th>
          <th style="width: 40px">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% positions.each do |position| %>
          <tr>
            <td><%= position.id %></td>
            <td><%= position.name %></td>
            <td><span class="badge badge-success">Ativo</span></td>
            <td><%= position.created_at&.strftime("%d/%m/%Y") %></td>
            <td>
              <%= link_to "Visualizar", position, class: "btn btn-sm btn-info" %>
              <% if current_user == position.company.user %>
                <%= link_to "Editar", edit_position_path(position), class: "btn btn-sm btn-primary" %>
                <%= link_to "Excluir", position, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/companies/components/_form.html.erb
<%= simple_form_for(@company, class: "contents", data: { turbo_frame: "_top" })  do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="card-body">
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :url %>

      <div class="row">
        <div class="col-md-6">
          <%= f.input :founded_date, as: :date, html5: true %>
        </div>
        <div class="col-md-6">
          <%= f.input :employee_count %>
        </div>
      </div>

      <%= f.input :summary, input_html: { rows: 5} %>

      <div class="row">
        <div class="col-md-6">
          <%= f.input :contact_email %>
        </div>
        <div class="col-md-6">
          <%= f.input :contact_phone %>
        </div>
      </div>

      <div class="form-group">
        <%= render "companies/components/image_form", f: f %>
      </div>
    </div>
  </div>

  <div class="card-footer text-right">
    <%= f.submit "Salvar", class: "btn btn-primary" %>
    <%= link_to "Cancelar", companies_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/companies/components/_image_form.html.erb
<%= f.label :logo, "Logo do PDV", class: "form-label" %>

<% if @company.logo.attached? %>
  <div class="col">
    <%= image_tag @company.logo, class: "img-fluid mb-2", style: "max-height: 400px" %>
  </div>
<% end %>

<%# TODO: fix - When company updated, logo is remove %>

<div class="dropzone dropzone-default dz-clickable" data-controller="dropzone"
                                                    data-dropzone-max-file-size="1"
                                                    data-dropzone-accepted-files="image/*"
                                                    data-dropzone-max-files="1"
                                                    data-upload-multiple="false">
  <%= f.file_field :logo, direct_upload: true, data: { dropzone_target: 'input' } %>
</div>

<% if f.object.errors.has_key?(:logo) %>
  <div class="invalid-feedback d-block"> <%= f.object.errors[:logo].join(", ") %></div>
<% end %>