config/routes.rb
Rails.application.routes.draw do
  resources :resumes
  root 'positions#index'
  devise_for :users

  resources :applicants
  resources :positions do
    resources :applicants, only: [:index], controller: 'positions_applicants'
  end
  resources :companies do
    resources :positions, only: [:index], controller: 'companies_positions'
  end
end

app/models/resume.rb
# == Schema Information
#
# Table name: resumes
#
#  id         :uuid             not null, primary key
#  summary    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :uuid             not null
#
# Indexes
#
#  index_resumes_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Resume < ApplicationRecord
  belongs_to :user
  has_many :experiences
  has_many :educations
  has_many :skills
  has_many :languages

  accepts_nested_attributes_for :experiences, :educations, :skills, :languages, allow_destroy: true
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: %i[show edit update destroy]

  def index
    @resumes = current_user.resumes
  end

  def show; end

  def new
    @resume = current_user.build_resume
    @resume.experiences.build
    @resume.educations.build
    @resume.skills.build
    @resume.languages.build
  end

  def edit; end

  def create
    @resume = current_user.build_resume(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to resume_url(@resume), notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to resume_url(@resume), notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resume.destroy!

    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_resume
    @resume = current_user.resumes.find(params[:id])
  end

  def resume_params
    params.require(:resume).permit(
      :summary,
      experiences_attributes: %i[id company_name position start_date end_date description _destroy],
      educations_attributes: %i[id school_name degree field_of_study start_date end_date _destroy],
      skills_attributes: %i[id name proficiency _destroy],
      languages_attributes: %i[id name proficiency _destroy]
    )
  end
end

app/views/resumes/_form.html.erb
<%= simple_form_for(@resume) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :summary %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/resumes/_resume.html.erb
<div id="<%= dom_id resume %>">
  <p>
    <strong>Summary:</strong>
    <%= resume.summary %>
  </p>

  <p>
    <strong>User:</strong>
    <%= resume.user_id %>
  </p>

</div>

app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render "form", resume: @resume %>

<br>

<div>
  <%= link_to "Show this resume", @resume %> |
  <%= link_to "Back to resumes", resumes_path %>
</div>

app/views/resumes/index.html.erb
<h1>Resumes</h1>

<div id="resumes">
  <% @resumes.each do |resume| %>
    <%= render resume %>
    <p>
      <%= link_to "Show this resume", resume %>
    </p>
  <% end %>
</div>

<%= link_to "New resume", new_resume_path %>

app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render "form", resume: @resume %>

<br>

<div>
  <%= link_to "Back to resumes", resumes_path %>
</div>

app/views/resumes/show.html.erb
<%= render @resume %>

<div>
  <%= link_to "Edit this resume", edit_resume_path(@resume) %> |
  <%= link_to "Back to resumes", resumes_path %>

  <%= button_to "Destroy this resume", @resume, method: :delete %>
</div>